spring:
  application:
    name: ibm_mq_listener
  datasource:
    url: jdbc:postgresql://localhost:5432/habrdb
    driver-class-name: org.postgresql.Driver
    username: habrpguser
    password: pgpwd4habr
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9090

ibm:
  mq:
    user: admin
    password: passw0rd
    queue-manager: QM1
    channel: DEV.ADMIN.SVRCONN
    conn-name: localhost(1414)
    use-authentication-m-q-c-s-p: false