spring:
  application:
    name: ibm_mq_listener
server:
  port: 9090

ibm:
  mq:
    user: admin
    password: passw0rd
    queue-manager: QM1
    channel: DEV.ADMIN.SVRCONN
    conn-name: localhost(1414)
    use-authentication-m-q-c-s-p: false